name: JUST
channels:
  - defaults
  - conda-forge
dependencies:
  - coverage
  - altair=4.1.0
  - matplotlib=3.1.1
  - numba=0.46.0
  - numpy=1.17.3
  - python=3.7.5
  - pandas=1.2.3
  - scikit-learn==0.24.1
  - jupyter
  - dash-bootstrap-components==0.11.3
